version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  pgdata:
