CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password_hash VARCHAR NOT NULL,
  role VARCHAR NOT NULL,
  first_name VARCHAR NOT NULL DEFAULT '',
  last_name VARCHAR NOT NULL DEFAULT ''
)